export const GET_ALL_PRODUCTS_LOADING = 'GET_ALL_PRODUCTS_LOADING'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const INCREASE_LIMIT = 'INCREASE_LIMIT'
export const INITIAL_LIMIT = 1
export const INITIAL_LIMIT_INCREASE = 1